# Application properties that need to be
# embedded within the web application can be included here

cas:
    authn:
        accept:
            users: "admin::admin,test1::test,test2::test"
    theme:
        #paramName: theme
        defaultThemeName: evegents
